### ISSUE TITLE
Predict all 4 corners for arbitary quadrilateral

### ISSUE THREAD

**Issue by SohamTamba** [zzzxxxttt/pytorch_simple_cornernet#3]
Hello,

I want to modify the code so that it cant detect any arbitary quadrilateral instead of a rectangle parallel to the axis of the image.

Is such an implementation already available?
If not any advice or doing so?

**Comment by zzzxxxttt** [comment]
@SohamTamba Well, you need to modify the dataset class to generate target heatmaps according to your task, and remove the corner pooling module since (maybe) it is not useful for detecting arbitrary quadrilateral targets. 

You can take a look at [ExtremeNet](https://github.com/xingyizhou/ExtremeNet), which I believe is very similar to your need.

**Comment by SohamTamba** [comment]
Thanks
